### ISSUE TITLE
Plug-In Fails to Unpack when uploaded

### ISSUE THREAD

**Issue by clayhagler** [AzureAD/active-directory-b2c-wordpress-plugin-openidconnect#10]
After downloading the current .zip and uploading to WP I get this error:

Could not copy file. active-directory-b2c-wordpress-plugin-openidconnect-master/vendor/phpunit/php-code-coverage/PHP/CodeCoverage/Report/HTML/Renderer/Template/coverage_bar.html.dist

**Comment by vonlar** [comment]
Try shortening the zip file name.  Likely the whole path is too long.

**Comment by clayhagler** [comment]
Highly likely as not even windows 10 can unpack it.

**Comment by clayhagler** [comment]
Need re-commit with shorter foldername

**Comment by gsacavdm** [comment]
As indicated by @vonlar , renaming the zip before uploading addresses this for Windows.
The name of the zip is controlled by the name of the repo which we won't be changing at this time, therefore, closing the issue.
