### ISSUE TITLE
License is not specified

### ISSUE THREAD

**Issue by georged** [AzureAD/active-directory-b2c-wordpress-plugin-openidconnect#17]
There is no licensing information provided for the plugin, the [plugin code](https://github.com/AzureAD/active-directory-b2c-wordpress-plugin-openidconnect/blob/master/b2c_authentication.php) states that the license is TBD so it's unclear what license does the plugin fall under. This is quite important when it's used on commercial projects (our customer flagged the license absence as an issue).

Can someone please add appropriate license information to the project?

Thanks!

**Comment by gsacavdm** [comment]
Fixed! Good catch!
