### ISSUE TITLE
PHP Fatal error in class-b2c-endpoint-handler.php

### ISSUE THREAD

**Issue by DariuszPorowski** [AzureAD/active-directory-b2c-wordpress-plugin-openidconnect#7]
Fatal error: Cannot use object of type WP_Error as array in D:\home\site\wwwroot\wp-content\plugins\aadb2c\class-b2c-endpoint-handler.php on line 24

**Comment by vonlar** [comment]
So this project isn't being maintained.  It seems it was written by interns and no one at Microsoft has picked it up.  Or at least I can't find anyone that has.

**Comment by psignoret** [comment]
@DariuszPorowski, can you provide some more details? At which point do you get this error message? How have you configured the plugin?

**Comment by vonlar** [comment]
@psignoret btw I've forked and fixed one bug (in two locations).  It might have been an issue with project name, but have a suspicion that it was more a bug in the code.

There also needs to be some work done when WordPress is configured as a bfolder off the root domain, which makes this plugin incompatible unless you change a few hard coded folder paths.

**Comment by gsacavdm** [comment]
We've checked in a bunch of improvements on this sample. I'm going to close this issue, let us know if you still have problems with the sample.
