### ISSUE TITLE
Ability to handle WordPress sites that aren't at root URL

### ISSUE THREAD

**Issue by vonlar** [AzureAD/active-directory-b2c-wordpress-plugin-openidconnect#9]
There's a few places that are hard coded that require WordPress to be at the root URL location.

**Comment by gsacavdm** [comment]
I believe I've addressed this (my site was running at http://localhost/wp).
See

https://github.com/AzureAD/active-directory-b2c-wordpress-plugin-openidconnect/blob/dc3cc648ba1e5d24a3db1af6d771fcbd10424d98/class-b2c-settings.php#L33

https://github.com/AzureAD/active-directory-b2c-wordpress-plugin-openidconnect/blob/59d141c81d0b1139f817cb2c7f572e3285f72e54/b2c_authentication.php#L163

Does this address your concerns?

**Comment by vonlar** [comment]
Here's two lines I'm concerned with.

https://github.com/AzureAD/active-directory-b2c-wordpress-plugin-openidconnect/blob/master/b2c_authentication.php#L27

https://github.com/AzureAD/active-directory-b2c-wordpress-plugin-openidconnect/blob/master/b2c_authentication.php#L179

I'm in a tough spot, as I have it running on my site at the moment without the changes.  I'll likely won't be able to test the updates for a week or two.  Always Gerardo, excellent job and thank you for taking the project over!

**Comment by gsacavdm** [comment]
I've removed the first L#27 since this is no longer being used.
I'll investigate the second later.

Thanks for taking the time to provide feedback and help others!

**Comment by gsacavdm** [comment]
Took care of second as well.

First handled with 06befa758
Second handled with 65195ce19

**Comment by vonlar** [comment]
Thanks!  Super awesome job.  I have it in my calendar to test and implement in 2 weeks.
